# Site settings
title:              "Ian Davis' Portfolio"
email:              "Ian@ianDrobo.com"
description:        "The Project Portfolio of Ian Davis"
url:                "https://idtx314.github.io"
baseurl:            "/"

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
